Repository tilucasoli/SquirrelStorage, pull requests merged in 2020-10, with the labels that each got.

#8 Feature/edit
  SquirrelStorage.xcodeproj/project.pbxproj
  SquirrelStorage/Controller/AddProductViewController.swift
  SquirrelStorage/Controller/EditProductViewController.swift
  SquirrelStorage/Controller/EstoqueViewController.swift
  SquirrelStorage/Controller/ProductDetailViewController.swift
  SquirrelStorage/Extension/UIButton.swift
  SquirrelStorage/Extension/UIImageView.swift
  SquirrelStorage/Model/Product.swift
  SquirrelStorage/SceneDelegate.swift
  SquirrelStorage/Service/Database.swift
  SquirrelStorage/View/ProdutoCollectionViewCell.swift
Labels: enhancement

#9 Fix/cleanup
  README.md
  SquirrelStorage.xcodeproj/project.pbxproj
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/Contents.json
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/Grupo 772.png
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/SSIcon_120-1.png
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/SSIcon_120.png
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/SSIcon_180.png
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/SSIcon_58.png
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/SSIcon_80.png
  SquirrelStorage/Assets.xcassets/AppIcon.appiconset/SSIcon_87.png
  SquirrelStorage/Controller/AddProductViewController.swift
  SquirrelStorage/Controller/EstoqueViewController.swift
  SquirrelStorage/Controller/FiltroViewController.swift
Labels: enhancement

#10 fixing what my friend fixed and I broke
  SquirrelStorage/Controller/EstoqueViewController.swift
  SquirrelStorage/Controller/FiltroViewController.swift
Labels: bug

#13 Delete Button Improvements
  SquirrelStorage/Controller/EditProductViewController.swift
  SquirrelStorage/Controller/EstoqueViewController.swift
Labels: bug, enhancement

#14 Dev
  SquirrelStorage.xcodeproj/project.pbxproj
  SquirrelStorage/Controller/FiltroViewController.swift
  SquirrelStorage/Info.plist
Labels: enhancement

#15 Fix/swift lint
  .swiftlint.yml
  SquirrelStorage/AppDelegate.swift
  SquirrelStorage/Controller/AddProductViewController.swift
  SquirrelStorage/Controller/EditProductViewController.swift
  SquirrelStorage/Controller/EstoqueViewController.swift
  SquirrelStorage/Controller/FiltroViewController.swift
  SquirrelStorage/Controller/HalfModalView.swift
  SquirrelStorage/Extension/UIViewSnapshot.swift
  SquirrelStorage/Service/ImageFetcher.swift
  SquirrelStorage/View/AddProductTableViewCell/CategoryTableViewCell.swift
  SquirrelStorage/View/AddProductTableViewCell/ImageTableViewCell.swift
  SquirrelStorage/View/AddProductTableViewCell/NameTableViewCell.swift
  SquirrelStorage/View/AddProductTableViewCell/QuantityTableViewCell.swift
  SquirrelStorage/View/ProdutoCollectionViewCell.swift
  SquirrelStorage/View/StarAnimationView.swift
Labels: enhancement

#16 Fix/filtro
  SquirrelStorage/Controller/EstoqueViewController.swift
  SquirrelStorage/Controller/FiltroViewController.swift
  SquirrelStorage/View/ProdutoCollectionViewCell.swift
Labels: enhancement

#17 Fix/image release
  SquirrelStorage/Controller/AddProductViewController.swift
  SquirrelStorage/Controller/EditProductViewController.swift
  SquirrelStorage/Controller/ProductDetailViewController.swift
  SquirrelStorage/Extension/UIButton.swift
  SquirrelStorage/Extension/UIImageView.swift
  SquirrelStorage/Model/Product.swift
  SquirrelStorage/Service/ImageFetcher.swift
  SquirrelStorage/View/AddProductTableViewCell/ImageTableViewCell.swift
  SquirrelStorage/View/ProductDetailView.swift
  SquirrelStorage/View/ProdutoCollectionViewCell.swift
Labels: enhancement

#18 now decimal pad with brazil locale works
  SquirrelStorage.xcodeproj/project.pbxproj
  SquirrelStorage/Controller/AddProductViewController.swift
  SquirrelStorage/Extension/String.swift
Labels: bug, enhancement

#19 Feature/decimal upgrade
  SquirrelStorage.xcodeproj/project.pbxproj
  SquirrelStorage/Controller/AddProductViewController.swift
  SquirrelStorage/Extension/Decimal.swift
  SquirrelStorage/Extension/Int.swift
  SquirrelStorage/Extension/String.swift
  SquirrelStorage/Model/Product.swift
  SquirrelStorage/View/ProdutoCollectionViewCell.swift
Labels: enhancement

#20 Fix/filtro
  SquirrelStorage/AppDelegate.swift
  SquirrelStorage/Controller/FiltroViewController.swift
  SquirrelStorage/View/AgruparFiltroCollectionViewCell.swift
  SquirrelStorage/View/EmptyState.swift
  SquirrelStorage/View/ProdutoCollectionViewCell.swift
Labels: enhancement

#21 Fix/picker category
  SquirrelStorage/Controller/EditProductViewController.swift
  SquirrelStorage/View/AddProductTableViewCell/CategoryTableViewCell.swift
Labels: bug, enhancement
